# miniconda bootstrap from conda-forge recipe
matrix:
  fast_finish: true

environment:
  matrix:
    - CONDA_PY: 35
      CONDA_INSTALL_LOCN: "C:\\Miniconda35-x64"
    - CONDA_PY: 36
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"
    - CONDA_PY: 37
      CONDA_INSTALL_LOCN: "C:\\Miniconda37-x64"
    - CONDA_PY: 38
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64" # Install in 36 because 38 doesn't exist right now.

platform:
  - x64

build: off

install:
  - cmd: call %CONDA_INSTALL_LOCN%\\Scripts\\activate.bat
  - cmd: set CONDA_PY=%CONDA_PY%
  - cmd: set CONDA_PY_SPEC=%CONDA_PY_SPEC%
  - cmd: conda config --set show_channel_urls true
  - cmd: conda config --add channels conda-forge
  #- cmd: conda update --yes --quiet conda
  - cmd: conda install -y pyzmq tornado jupyter_client nbformat nbconvert ipykernel pip nose
  - cmd: pip install .[test]
# FIXME: Use patch for python 3.8, windows issues (https://github.com/ipython/ipykernel/pull/456) - remove once released
  - IF %CONDA_PY% == 38 pip install --upgrade git+https://github.com/ipython/ipykernel.git

test_script:
  - pytest
